# Generated by Django 4.0.4 on 2022-11-29 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='choco_tbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnm', models.CharField(max_length=40)),
                ('cpic', models.FileField(upload_to='pictures')),
                ('cprc', models.IntegerField()),
            ],
        ),
    ]
